MONGO_URI="mongodb+srv://alfiSkibidi:alfi123@belajarcrud.p8wz7lk.mongodb.net/?retryWrites=true&w=majority&appName=BelajarCRUD"
PASSWORD_HASH_KEY="oawkoakwokwaokaowkoawk"
COOKIE_HASH_KEY="truongbienuhuyhuhuyhhhhh"
GROQ_API_KEY ="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"
OPENAI_API_KEY ="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"